# 参考文档： https://www.xuxueli.com/xxl-job
version: "3"
services:
  xxl-job-admin:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/xxl-job-admin:2.3.0 # 原镜像`xuxueli/xxl-job-admin:2.3.0`
    container_name: xxl-job-admin
    environment:
      # TODO 根据自己的配置修改，配置项参考源码文件：/xxl-job/xxl-job-admin/src/main/resources/application.properties
      PARAMS: "--spring.datasource.url=jdbc:mysql://192.168.1.59:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
               --spring.datasource.username=root
               --spring.datasource.password=123456
               --server.servlet.context-path=/xxl-job-admin"
    ports:
      - "8080:8080"
    volumes:
      - ./xxl-job/logs/:/data/applogs/xxl-job/