version: "3.9"
services:
 postgres:
  image: postgis/postgis:13-master
  container_name: postgres
  restart: always
  environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
  ports:
    - 5432:5432
  volumes:
    - ./postgres/data:/var/lib/postgresql/data

